#!/bin/bash

# sudo apt install screen build-essential
# sudo yum -y install glibc-static libstdc++-static
# sudo ufw allow 37016
# sudo ufw allow 3690

gcc -static -std=c++11 -O3 -o fly-server-test-port fly-server-test-port.cpp \
 CivetServer.cpp \
 civetweb.c \
 CDBManager.cpp  \
 jsoncpp/jsoncpp.cpp \
 ./zlib/adler32.c \
 ./zlib/compress.c \
 ./zlib/crc32.c \
 ./zlib/deflate.c \
 ./zlib/gzclose.c \
 ./zlib/gzlib.c \
 ./zlib/gzread.c \
 ./zlib/gzwrite.c \
 ./zlib/infback.c \
 ./zlib/inffast.c \
 ./zlib/inflate.c \
 ./zlib/inftrees.c \
 ./zlib/trees.c \
 ./zlib/uncompr.c \
 ./zlib/zutil.c \
 -I ./jsoncpp/include \
 -D_REENTRANT \
 -D_NDEBUG \
 -lstdc++ -lpthread -ldl -lm

